#https端口号.
server.port: 1443
#证书的路径.
server.ssl.key-store: classpath:baeldung.p12
#证书密码，请修改为您自己证书的密码.
server.ssl.key-store-password: 159357
#秘钥库类型
server.ssl.keyStoreType: PKCS12
#证书别名
server.ssl.keyAlias: baeldung